on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: docker
    strategy:
      matrix:
        sm-version: [ '1.11.x', '1.12.x', '1.13.x']
    name: Sourcemod v${{ matrix.sm-version }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup sourcepawn
        uses: https://github.com/rumblefrog/setup-sp@bb7306e551914d48b2d8405dba17ddc46a4a12a2
        with:
          version: ${{ matrix.sm-version }}
      - name: Build Plugins
        env:
          SPCOMP_PATH: spcomp
        run: chmod +x compile_all.sh && ./compile_all.sh
      - name: Perform release
        uses: actions/forgejo-release@v2.7.3
        with:
          direction: upload
          release-dir: plugins/
          release-notes-assistant: true
