/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface MapInfoEntity {
  'chapter_count'?: number | null;
  
  /* 1:official */
  'flags'?: number | null;
  'mapid': string;
  'mission_id'?: string | null;
  'name': string;
}
export interface MapRatingsEntity {
  'comment'?: string | null;
  'map_id': string;
  'steamid': string;
  'value': number;
}
export interface StatsGamesEntity {
  'used_adrenaline'?: number;
  'BoomedTeammates'?: number;
  'kills_boomer'?: number | null;
  'used_bile'?: number;
  
  /* unique campaign session id */
  'CarAlarmsActivated'?: number;
  'character_type'?: number | null;
  'kills_charger'?: number | null;
  'ClearedPinned'?: any | null;
  'DamageDealt'?: number;
  'damage_taken'?: number;
  'DamageToTank'?: any;
  'DamageToWitch'?: any;
  'date_end': string;
  
  /* when campaign started */
  'date_start'?: string | null;
  'Deaths'?: number;
  'used_defib'?: number;
  'difficulty'?: number;
  
  /* in minutes */
  'duration'?: number | null;
  'finale_time': number;
  'used_kit_other'?: number;
  'flags'?: number;
  'gamemode'?: string | null;
  'honks'?: number | null;
  'kills_hunter'?: number | null;
  'HuntersDeadstopped'?: any;
  'id'?: string;
  'Incaps'?: number;
  'kills_jockey'?: number | null;
  
  /* when user first joined game */
  'join_time': string;
  
  /* the map id */
  'map': string;
  'used_kit_self'?: number;
  'kills_melee'?: number;
  'minutes_idle'?: any;
  'used_molotov'?: number;
  'used_pills'?: number;
  'ping'?: number | null;
  'used_pipebomb'?: number;
  'times_revived_other'?: number;
  'RocksDodged'?: any;
  'RocksHitBy'?: any;
  'server_tags'?: string | null;
  'kills_smoker'?: number | null;
  'SmokersSelfCleared'?: any;
  'SpecialInfectedKills'?: number | null;
  'kills_spitter'?: number | null;
  'steamid': string;
  'damage_dealt_friendly'?: number;
  'damage_dealt_friendly_count'?: any;
  'damage_taken_friendly_count'?: number | null;
  'damage_taken_friendly'?: number | null;
  'TimesBoomed'?: any;
  'TimesPinned'?: any;
  'top_weapon'?: string | null;
  'WitchesCrowned'?: any;
  'ZombieKills'?: number;
}
export interface StatsHeatmapsEntity {
  'id'?: number;
  'map': string;
  'steamid': string;
  'timestamp'?: number;
  'type': number;
  'x'?: number | null;
  'y'?: number | null;
  'z'?: number | null;
}
export interface StatsPointsEntity {
  'amount': number;
  'id'?: number;
  'steamid': string;
  'timestamp': number;
  'type': number;
}
export interface StatsUsersEntity {
  'adrenaline_used'?: number;
  'boomer_mellos'?: number | null;
  'boomer_mellos_self'?: number | null;
  'caralarms_activated'?: number;
  
  /* Times cleared a survivor thats pinned */
  'cleared_pinned'?: number;
  'clowns_honked'?: number;
  'common_headshots'?: number;
  'kills_common'?: number | null;
  'connections'?: number;
  'country': string;
  'created_date': string;
  'damage_as_tank'?: number;
  'damage_molotov'?: number;
  'damage_to_tank'?: number | null;
  'damage_witch'?: number;
  'defibs_used'?: number;
  'door_opens'?: number;
  'kills_ff'?: number;
  'finales_won'?: number;
  'forgot_kit_count'?: number;
  'heal_others'?: number;
  'heal_self'?: number;
  'hunters_deadstopped'?: number;
  'infected_damage_give'?: string;
  'infected_damage_rec'?: string;
  'infected_deaths'?: number;
  'kills_all_specials'?: number | null;
  'kills_boomer'?: number;
  'kills_charger'?: number;
  'kills_hunter'?: number;
  'kills_jockey'?: number;
  'kills_minigun'?: number;
  'kills_molotov'?: number;
  'kills_pipe'?: number;
  'kills_smoker'?: number;
  'kills_spitter'?: number;
  'kills_witch'?: number;
  'kits_slapped'?: number;
  'last_alias': string;
  'last_join_date': string;
  'kills_melee'?: number | null;
  'minutes_idle'?: any;
  'minutes_played'?: number;
  'packs_used'?: number;
  'pickups_molotov'?: number;
  'pickups_pain_pills'?: number;
  'pickups_pipe_bomb'?: number;
  'pills_used'?: number;
  'points'?: number;
  'region'?: string | null;
  
  /* Times themselves revived */
  'revived'?: number;
  'revived_others'?: number;
  'rocks_hitby'?: number;
  'smokers_selfcleared'?: number;
  'steamid': string;
  'survivor_damage_give'?: string;
  'survivor_damage_rec'?: string;
  'survivor_deaths'?: number;
  'survivor_ff'?: number;
  'survivor_ff_rec'?: number | null;
  'survivor_incaps'?: number;
  'tanks_killed'?: number;
  'tanks_killed_melee'?: number;
  'tanks_killed_solo'?: number;
  'throws_molotov'?: number;
  'throws_pipe'?: number;
  'throws_puke'?: number;
  'times_pinned'?: number;
  'total_distance_travelled'?: number | null;
  'witches_crowned'?: number;
  'witches_crowned_angry'?: number;
}
export interface StatsWeaponsUsageEntity {
  'headshots'?: number | null;
  'kills'?: number | null;
  'minutesUsed'?: number | null;
  'steamid': string;
  'totalDamage': string;
  'weapon': string;
}


export interface Player {
  steamid: string,
  name: string,
}