export type ColorType = "is-primary"
    | "is-link"
    | "is-info"
    | "is-success"
    | "is-warning"
    | "is-danger"
    | "is-black"
    | "is-dark"
    | "is-light"
    | "is-white"


export type TextColor = "has-text-primary"
    | "has-text-primary-light"
    | "has-text-info"
    | "has-text-info-light"
    | "has-text-success"
    | "has-text-success-light"
    | "has-text-warning"
    | "has-text-warning-light"
    | "has-text-danger"
    | "has-text-danger-light"
    | "has-text-light"
    | "has-text-lighter"
    | "has-text-white"
    | "has-text-black"

export type BackgroundColor = "has-background-primary"
    | "has-background-primary-light"
    | "has-background-info"
    | "has-background-info-light"
    | "has-background-success"
    | "has-background-success-light"
    | "has-background-warning"
    | "has-background-warning-light"
    | "has-background-danger"
    | "has-background-danger-light"
    | "has-background-light"
    | "has-background-lighter"
    | "has-background-white"
    | "has-background-black"

export type Size = "is-small" | "is-medium" | "is-large"